### ISSUE TITLE
How to connect to obsidian as a server?

### ISSUE THREAD

**Issue by Archie-2021** [TheseusGrey/edit-in-neovim#1]
Hey,

It is working fine when I enable "Open at Startup" option, but what if I want to connect to obsidian after closing that instance of nvim?

I thought something like 'nvim --server localhost:<myport>` would work , but not working for me after closing the instance. Is it close the port after disconnecting?

Thanks for this very handy plugin

**Comment by TheseusGrey** [comment]
Hi @Archie-2021,

It's actually Neovim acting as the server not Obsidian. So you'd need to use the `--listen` flag rather than `--server`. I was alil confused by this at first :sweat_smile: but I understand it as:

- `nvim --listen <PORT/SOCKET>` => make this neovim instance listen on this port/socket.
- `nvim --server <PORT/SOCKET>` => send a message to the neovim instance listening at the given port/socket.

I can add a command to the plugin so you can re-open the instance within obsidian to streamline this process (or if you want to have a go be my guest :slightly_smiling_face:).

**Comment by Archie-2021** [comment]
> Hi @Archie-2021,
> 
> It's actually Neovim acting as the server not Obsidian. So you'd need to use the `--listen` flag rather than `--server`. I was alil confused by this at first 😅 but I understand it as:
> 
> * `nvim --listen <PORT/SOCKET>` => make this neovim instance listen on this port/socket.
> * `nvim --server <PORT/SOCKET>` => send a message/connect to the neovim instance listening at the given port/socket.
> 
> I can add a command to the plugin so you can re-open the instance within obsidian to streamline this process ~(or if you want to have a go be my guest 🙂)~, I ended up adding the command myself after writing since it was only a couple lines so I can get the release out incase others have a similar issue to yourself 😅.

It is confusing how it works.
Yeah I appreciate if you add the command to obsidian, that would make life so much easier.

I will play around with this feature tho as it seems interesting.
Thanks

**Comment by TheseusGrey** [comment]
No worries, if there's nothing else i'll close this issue 🙂

**Comment by Archie-2021** [comment]
> No worries, if there's nothing else i'll close this issue 🙂

Yeah I think I am good on this issue. Thanks

**Comment by Archie-2021** [comment]
@TheseusGrey 
Hey, 
I thought not creating a new issue because it is related.

This new command you added opens neovim correctly, but need a update of active Obsidian file to activate and show. I think this doesn't happen we launch nvim at start up.
Thanks

**Comment by TheseusGrey** [comment]
Hi Archie,

Thanks for the feedback. I'll re-open this issue for it and get a new release out when I have time 🙂

**Comment by TheseusGrey** [comment]
[New release](https://github.com/TheseusGrey/edit-in-neovim/releases/tag/1.1.5) is out, now it should open the active file in Obsidian as a neovim buffer when you run the command. 

If there's any issues just let me know, otherwise I'll mark this as closed :slightly_smiling_face:

**Comment by Archie-2021** [comment]
Works like a charm now, thank you
