### ISSUE TITLE
This plugins opens a separate nvim server in backgroup when not active

### ISSUE THREAD

**Issue by Archie-2021** [TheseusGrey/edit-in-neovim#7]
Hello,

Yesterday I noticed a problem, I was about to shutdown my computer and I noticed I am using a lot of RAM eventho I have closed all the windows. 
I looked into processes and it seems like this plugin starts up nvim instances eventho I didn't used it (it is not set to open on startup for me)

Here you can see it again , on a fresh boot and after launching Obisdian:

```
$  pgrep -a nvim

36125 /usr/bin/nvim --server 127.0.0.1:2006 --remote Z_Utility/Workbench-center/240729T201958.excalidraw.md
41034 /usr/bin/nvim --server 127.0.0.1:2006 --remote 2_Library/00-Apps/taskwarrior_240523T092133.md
```
Looks like every time I switch to a new leaf it start one process for it in background.

**Comment by TheseusGrey** [comment]
Hi Archie,

Ah yes thank you for spotting this. I can put out a release to prevent it from trying to open the file in neovim if the listening instance isn't running 🙂

**Comment by Archie-2021** [comment]
> Hi Archie,
> 
> Ah yes thank you for spotting this. I can put out a release to prevent it from trying to open the file in neovim if the listening instance isn't running 🙂

Hi,
Looking forward for the patch man, thanks

**Comment by TheseusGrey** [comment]
Released the new version, since there's been no new comments I'm gonna close this as completed :slightly_smiling_face:
