### ISSUE TITLE
Problem with tmux

### ISSUE THREAD

**Issue by lazy-dinosaur** [TheseusGrey/edit-in-neovim#8]
Since the last update, I haven't been able to use the plugin properly.

I'm currently using tmux and the obsidian.nvim plugin. I'm using a callback function from obsidian.nvim to connect with the plugin. Here is my code:
```lua
      callbacks = {
        -- Runs at the end of `require("obsidian").setup()`.
        ---@param client obsidian.Client
        post_setup = function(client)
          require("render-markdown").enable()
          -- If you want to use "~", you need to prefix the vault path with vim.fn.expand "~"
          local vault_location = require("obsidian")._client.dir.filename
          local file_location = vault_location .. "/**.md"
          local group = vim.api.nvim_create_augroup("obsidian_cmds", { clear = true })
          vim.api.nvim_create_autocmd("BufAdd", {
            command = "ObsidianOpen",
            pattern = { file_location },
            group = group,
            desc = "Opens the current buffer in Obsidian",
          })

          local api = vim.api
          local fn = vim.fn

          -- 전역 변수로 서버가 시작되었는지 여부를 저장
          local server_started = false

          -- 서버 시작 함수
          local function start_server()
            if not server_started then
              local address = "127.0.0.1:2006"
              local server_started_flag = pcall(fn.serverstart, address)
              if server_started_flag == true then
                print("Server started at " .. address)
                server_started = true -- 서버가 성공적으로 시작되었으므로 플래그를 true로 설정
              else
                print("Failed to start server.")
              end
            end
          end

          local group = vim.api.nvim_create_augroup("obsidian_cmds", { clear = true })

          -- Autocmd 설정
          api.nvim_create_autocmd("BufAdd", {
            group = group,
            pattern = vault_location .. "/*", -- 패턴 수정
            callback = function()
              -- 현재 버퍼의 디렉토리를 확인하고 패턴과 일치하는 경우만 서버를 시작
              local current_file = api.nvim_buf_get_name(0)
              if current_file:find(vault_location .. "/") then
                start_server()
              end
            end,
            desc = "ObsidianServerStart",
          })
        end,
}
```
The problem is that the plugin isn't recognizing the Neovim server that's already running. Can we make the plugin check if the port is in use with a command like lsof -i :2006?

**Comment by TheseusGrey** [comment]
When you say it isn't recognizing the server that already running, do you mean file are not opened in the existing server? or that a second neovim instance gets opened by the plugin?

if it's the latter, you can just disable the "Open on startup" option. If it's the first option then I think I know what's causing it, I'll try and get a release out soon.

**Comment by TheseusGrey** [comment]
[Put out a new release](https://github.com/TheseusGrey/edit-in-neovim/releases/tag/1.1.16) which should hopefully resolve your issue. 

It wasn't so much an issue with tmux as it was with just having a neovim instance not managed by the plugin. Should work now but there are a couple things to bare in mind (which you probably already know but in case someone stumbles across this issue in future:
- The plugin doesn't care _what_ is using the port, only that it's open (the plugin can't tell what's using the port as of `1.1.16`)
- Neovim needs to have your vault's root directory as it's cwd (run neovim from your vaults root dir basically)

if things still don't work just let me know and I can take another look at it :slightly_smiling_face:
